[platformio]
default_envs = esp32dev

[env]
platform = espressif32
build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_WIDTH=320
  -D TFT_HEIGHT=240
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=21
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D LOAD_FONT6=1
  -D LOAD_FONT7=1
  -D LOAD_FONT8=1
  -D LOAD_GFXFF=1
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=20000000

[env:esp32dev]
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
  ${env.build_flags}
  -std=gnu++17
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  bblanchon/ArduinoJson @ ^7.3.0

[env:native]
platform = native
test_framework = unity
test_build_src = true
test_filter = test_native_logic
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
lib_deps =
  bblanchon/ArduinoJson @ ^7.3.0
build_src_filter =
  +<src/domain/*>
  +<src/domain/**/*>
  +<src/app/scheduler.cpp>
  -<src/main.cpp>
  -<src/app/app_controller.cpp>
  -<src/infrastructure/*>
  -<src/platform/*>
  -<src/ui/*>

[env:embedded]
board = esp32dev
framework = arduino
test_framework = unity
test_filter = test_embedded_smoke
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
  ${env.build_flags}
  -std=gnu++17
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  bblanchon/ArduinoJson @ ^7.3.0
